### ISSUE TITLE
Use the exact same "mkl_dnn" version as cmake

### ISSUE THREAD

**Issue by ghost** [Vertexwahn/rules_oidn#7]
Error-source:

* oidn uses "mkl-dnn FORK(!!!) 2.2.4"
  * oidn uses a customized version of mkl-dnn
* bazel build uses "oneDNN-2.7.1"

## Confirmed

* version 2.7.1 does not compile within original oidn source-code

## Tasks

- [ ] Use mkl-dnn branch oidn `f53274c9fef211396655fc4340cb838452334089`
  - https://github.com/OpenImageDenoise/mkl-dnn/commits/oidn
- [ ] Attempt to update the existent bazel template to build an earlier version
  - https://github.com/tensorflow/tensorflow/blob/9159209df2b25da5393e457a7c57f9882e60ab69/third_party/mkl_dnn/mkldnn_v1.BUILD
- [ ] rewrite bazel build template for mkldnn for 2.2.4
- [ ] ... (workout an alternative solution)

**Comment by Vertexwahn** [comment]
https://github.com/Vertexwahn/rules_oidn/issues/1 was solved
